- name: mysql server setup
  hosts: mysql
  become: yes
  tasks:
    - name: install mysql server
      ansible.builtin.package:
        state: present
        name: mysql-server

    - name: restart the mysql service
      ansible.builtin.service:
        name: mysqld
        state: restarted
        enabled: yes
    - name: set the pass
      ansible.builtin.command: mysql_secure_installation --set-root-pass RoboShop@1
