- name: payment server setup
  hosts: payment
  become: yes
  tasks:
    - name: install python
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - python3
        - gcc
        - python3-devel

    - name: add roboshop user
      ansible.builtin.user:
        name: roboshop
        system: true
        shell: /sbin/nologin
        home: /app
        comment: roboshop system user

    - name: remove app
      ansible.builtin.file:
        path: /app
        state: absent

    - name: create app
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloading the payment file
      ansible.builtin.get_url:
        url: https://roboshop-artifacts.s3.amazonaws.com/payment-v3.zip
        dest: /tmp/payment.zip
    - name: unarchieve the file
      ansible.builtin.unarchive:
        src: /tmp/payment.zip
        dest: /app
        remote_src: yes

    - name: Install specified python requirements
      ansible.builtin.pip:
      requirements: /my_app/requirements.txt
